[supervisord]
nodaemon=true

[program:X11]
command=/usr/bin/Xvfb :0 -screen 0 %(ENV_RESOLUTION)sx24
autorestart=true
priority=10

[program:x11vnc]
command=/usr/bin/x11vnc -xkb -noxrecord -noxfixes -noxdamage -display :0 -forever -nopw -wait 5 -shared -permitfiletransfer -tightfilexfer -rfbport 5901
autorestart=true
priority=20

[program:novnc]
command=/usr/bin/novnc_server --vnc localhost:5901 --listen 6901
autorestart=true
priority=30

[program:fluxbox]
command=/usr/bin/fluxbox
autorestart=true
priority=40
environment=DISPLAY=":0"

[program:xrdp]
command=/usr/sbin/xrdp -n
autorestart=true
startretries=3
priority=50
